### ISSUE TITLE
CSV Writer header issue

### ISSUE THREAD

**Issue by kapilgurnani** [TekMonksGitHub/json_esb#11]
- Add headers every time when creating csv with multiple records.

Attaching screenshot of pipeline for reference
(https://user-images.githubusercontent.com/53506960/84627302-4de7fa80-af04-11ea-965e-ab32d7efe323.png)

**Comment by TekMonksGitHub** [comment]
Can you check this flow -> the code is created to skip headers on append

https://github.com/TekMonksGitHub/ASB/blob/master/flows/pipeline_RESTtoCSV.json

Specifically, if the file exists already - then it will not write the headers to it
![image](https://user-images.githubusercontent.com/16070987/84631386-3f133f00-af28-11ea-9f71-0f48170eaed0.png)

**Comment by kapilgurnani** [comment]
Solution

- Wait till file creation

- After successfully creation of file we write remaining records

Attaching screenshot of updated code
(https://user-images.githubusercontent.com/53506960/84631611-509a1e00-af0b-11ea-8e1e-7dee331a9cbb.png)

**Comment by TekMonksGitHub** [comment]
This fix this wrong. The file could have been created before current flow too, it will append headers to it again. It only checks flow environment to decide whether to append headers or not which is wrong.


- If the file exists, do NOT append headers
- If the file does not exist, but we have pending writes - only then append headers

Else just write the values.

**Comment by kapilgurnani** [comment]
Scenario

- We have 10 records for write in csv file

- File creation takes time so when second records come then it found file is not exists so it send request of record creation with headers also that the issue

Attaching a video which shows the exact issue

[csvwriter_issue.mp4.zip](https://github.com/TekMonksGitHub/ASB/files/4778914/csvwriter_issue.mp4.zip)

**Comment by TekMonksGitHub** [comment]
Yes so the solution will be to set an environmental flag -> but it can't be the only deciding factor. E.g. if the flag is not set, then also you may or **may not** want to write the headers depending on if the file existed or not.

**Comment by TekMonksGitHub** [comment]
Specifically, the code below is wrong because it says if the flag is not there write headers out - which would append headers to an existing file. 

![image](https://user-images.githubusercontent.com/16070987/84635982-f612b900-af2e-11ea-83ff-ff91664d3b9d.png)

**Comment by kapilgurnani** [comment]
We can set the environment variable as per filename

Attaching screenshot for reference
(https://user-images.githubusercontent.com/53506960/84642853-b04bf580-af1a-11ea-9e03-238c76c40860.png)

**Comment by TekMonksGitHub** [comment]
Rejected. This will still have an issue if the file doesn't exist, and if the environment variable is set. It won't write anything. Please test your code with modifications trying out every use case, before proposing a fix.

**Comment by kapilgurnani** [comment]
Now slightly change the logic and check the environment variable before fs.access()

- If env variable is false or not declared then makes it true otherwise return

- After finish write, then make that env variable false

Attaching screenshot for reference
![image](https://user-images.githubusercontent.com/53506960/84666112-4f361900-af3e-11ea-84a4-077f4d3a5812.png)

![image](https://user-images.githubusercontent.com/53506960/84666150-5a894480-af3e-11ea-8e83-f792e82e693b.png)

**Comment by TekMonksGitHub** [comment]
All you need to do is simple - set a flow env variable for the file that says headers are written, already.

fs.access {
... if (error) && if (!flow.env[routeName][fileName]) {
          flow.env[routeName] = {}; flow.env[routeName][fileName] = true; 
         {...writeHeaders};
writeFile(values)... 
} 

Something as simple as that!

**Comment by TekMonksGitHub** [comment]
Please retest and check if commit https://github.com/TekMonksGitHub/ASB/commit/bab201a8a79984e4dc6fbf764ed244aff47da085 solves this issue.
